### ISSUE TITLE
Use %GOPATH% environment variable instead of %HOME%\Go

### ISSUE THREAD

**Issue by RoestVrijStaal** [ebiten/ebiten.org#1]
See the 2nd https://ebiten.org/install.html#Option_2:_Without_Go_modules

`%HOME%` is not an official Windows environment variable (you likely meant `%USERPROFILE%`). 

However, using `%GOPATH%` is more foolproof, since not everyone has their Go workspace in their user's home directory (like me). Strangely enough, `%GOPATH%` was automatically created after (clean) installing go1.12.3. I just had to need to change its value to point to the right directory after installation.

Oh, and the `id`-attributes of the page's  `h3` aren't unique, which is kinda sad when someone wants to link to a separate section of the page.

**Comment by hajimehoshi** [comment]
Hi, thank you for pointing this out! I forgot that %HOME% is not defined by default :-)

> %HOME% is not an official Windows environment variable (you likely meant %USERPROFILE%).
> However, using %GOPATH% is more foolproof, since not everyone has their Go workspace in their user's home directory (like me). Strangely enough, %GOPATH% was automatically created after (clean) installing go1.12.3. I just had to need to change its value to point to the right directory after installation.

I didn't know that %GOPATH% is created automatically. As there is still a syncing issue you mentioned, 
using `go env GOPATH` sounds the most robust way. What do you think?

BTW, I don't know the counterpart in DOS of `$()` in the shell. Do you know that?

> Oh, and the id-attributes of the page's h3 aren't unique, which is kinda sad when someone wants to link to a separate section of the page.

This is a known issue, and GitHub Wiki has the same issue btw :-P Let me think...

**Comment by RoestVrijStaal** [comment]
@hajimehoshi 

About the GOPATH environment variable: I worded it poorly. The %GOPATH% environment variable has been added by the installer. But by default it points to the default profile directory of the user (%USERPROFILE%\Go). However, I like to have my source codes at one place at a different disk, so I needed to change %GOPATH% to my desired path.

So, given its initiated value, I think it is safe to use %GOPATH%

For the command substitution; placing the desired command in the iteration-source of a for loop, seems to mimic command substitution. I have also read putting commands in `( )`-es works as well, but the command will be executed in a subshell.

The other way is to put the desired commands in a separate batch file and call that batch file when needed.

Another way is to require MSYS2 environment and use the bash which comes with it. Yet another way is to use Powershell, since it got opensourced and available for popular Linux distros and MacOSX. However, till Win7 isn't EOL, you'll need to keep a PowerShell version clash in mind.

And awww too bad about the wiki :(

**Comment by hajimehoshi** [comment]
> About the GOPATH environment variable: I worded it poorly. The %GOPATH% environment variable has been added by the installer. But by default it points to the default profile directory of the user (%USERPROFILE%\Go). However, I like to have my source codes at one place at a different disk, so I needed to change %GOPATH% to my desired path.

Acknowledged.

> For the command substitution; placing the desired command in the iteration-source of a for loop, seems to mimic command substitution. I have also read putting commands in ( )-es works as well, but the command will be executed in a subshell.

That sounds a little tricky. I'd do setting `GOPATH` once and use it immediately. I'll fix the doc in this way later.

> And awww too bad about the wiki :(

I was wondering what you mean :)

**Comment by hajimehoshi** [comment]
> > And awww too bad about the wiki :(

> I was wondering what you mean :)

Ah, your reaction was about the duplicated header ids? Yes, that's too bad...

**Comment by hajimehoshi** [comment]
Now I omitted GOPATH way.
