### ISSUE TITLE
Install page doesn't mention needing GCC (Windows)

### ISSUE THREAD

**Issue by 1j01** [ebiten/ebiten.org#13]
https://ebiten.org/install.html

Following the instructions didn't work (`gcc` missing), but I found [this issue](https://github.com/hajimehoshi/ebiten/issues/479) suggesting TDM GCC.

After installing [TDM GCC](https://sourceforge.net/projects/tdm-gcc/) (`tdm64-gcc-5.1.0-2.exe`), and opening a fresh terminal window, it ran fine.

**Comment by hajimehoshi** [comment]
It is because Ebiten does not require C compilers on Windows :-)

**Comment by hajimehoshi** [comment]
> Following the instructions didn't work (gcc missing)

I was wondering if you used the latest Ebiten (after 1.9.x).

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this if you still find problems.

**Comment by 1j01** [comment]
How do I know what version I've installed, or to install a specific version?

I'm new to Go, and I went with the Option 2: Without Go modules (since it looked easier for trying it out)

**Comment by hajimehoshi** [comment]
> I went with the Option 2

Then I think you have the almost latest version of Ebiten and can work without C compilers.

**Comment by 1j01** [comment]
Alright, I looked up the error in my journal. (I should have shared this from the beginning.)
```
C:\Users\Isaiah\Other_Repositories\pixel-examples\platformer (master -> origin)
λ go get github.com/hajimehoshi/ebiten/...
# github.com/hajimehoshi/ebiten/mobile/ebitenmobileview
exec: "gcc": executable file not found in %PATH%
```
So it looks like it's from a sub-package for mobile support (which I don't need), but this is the command that's listed on the Install page (for Option 2).

I've gone with the Pixel framework for now, but let me know if you want me to uninstall GCC and try to reproduce this. (How recently was 1.9.x released? Maybe I just got an older version?)

**Comment by hajimehoshi** [comment]
> github.com/hajimehoshi/ebiten/mobile/ebitenmobileview

Ahh, this is the package that was added recently and is not needed for Windows. That should be a bug. I'll fix this asap! Thank you!

> but let me know if you want me to uninstall GCC and try to reproduce this. 

That's fine, maybe you'll need GCC again for other packages :-)

> How recently was 1.9.x released?

This was released in March this year. You can check the version by

```
cd C:\Users\Isaish\go\src\github.com\hajimehoshi\ebiten
git log
```

**Comment by hajimehoshi** [comment]
This should be fixed by the latest fix.

You don't have to uninstall GCC since it might be difficult. I'll try this later with a Windows machine without GCC. Thank you for reporting!
