### ISSUE TITLE
Use Firebase Hosting or other hosting services

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten/ebiten.org#17]
GitHub pages is slow.

**Comment by Ukrainec** [comment]
Github site quickly loads pages. This is noticeable, no expectations and a long download. I specifically checked the page load speed metric [host-tracker.com/InstantCheck/1/64077373-9df4-e911-828a-0003ff73517a/](https://www.host-tracker.com/InstantCheck/1/64077373-9df4-e911-828a-0003ff73517a/) This figure is 3.27 seconds, this can not be called slow loading.

**Comment by hajimehoshi** [comment]
HTML files or other text files don't matter, but Wasm binaries or image files matter. Wasm binaries for the examples are now on Google Cloud Storage, which is much faster than GitHub pages.

**Comment by hajimehoshi** [comment]
> host-tracker.com/InstantCheck/1/64077373-9df4-e911-828a-0003ff73517a/ 

I'm not sure we could use the same metrics of github.com for GitHub pages.
