### ISSUE TITLE
Incorrect link to the article, Matrix in Ebiten.

### ISSUE THREAD

**Issue by laskdkmg** [ebiten/ebiten.org#40]
https://ebiten.org/tour/geom.html

The link to Matrix in Ebiten should be https://ebiten.org/documents/matrix.html instead of https://ebiten.org/tour/matrix.html, thanks.

**Comment by hajimehoshi** [comment]
Good point, thank you!

**Comment by laskdkmg** [comment]
NP, and i just create a PR for it, https://github.com/ebiten/ebiten.org/pull/41.
Can you help me take a look?

BTW, the document is helpful to me, thanks.

**Comment by hajimehoshi** [comment]
> Can you help me take a look?

Sorry but I've already fixed the link.

> BTW, the document is helpful to me, thanks.

Thank you for the feedback!
