### ISSUE TITLE
Small typo?: Link to localhost on the webpage

### ISSUE THREAD

**Issue by pwiecz** [ebiten/ebiten.org#46]
On page https://ebiten.org/blog/resizable.html
Link in text: "Actually the mobile environments already has the same interface." leads to http://localhost:8000/documents/mobile.html
![image](https://user-images.githubusercontent.com/136140/83236771-5914f980-a194-11ea-841a-958b89c501c8.png)

**Comment by hajimehoshi** [comment]
Oops, this needs to be `/documents/mobile.html`.

I'll fix this later. Thanks!
