### ISSUE TITLE
Windows specific powershell build command.

### ISSUE THREAD

**Issue by tomlister** [ebiten/ebiten.org#48]
https://ebiten.org/documents/webassembly.html
`$env:GOOS="js"; $env:GOARCH="wasm"; go build -o yourgame.wasm`

**Comment by tomlister** [comment]
`$env:GOOS="js"; $env:GOARCH="wasm"; go build -o main.wasm .`
Use this one instead.

**Comment by hajimehoshi** [comment]
Thanks, but I've not determined to add this note. If I'd do, I'd want to add PowerShell scripts to all the shell scripts for consistency, but I could not maintain them.

**Comment by tomlister** [comment]
👍
