### ISSUE TITLE
(First ever issue, delete if wrong place) Tiling system changes after 1.12 update

### ISSUE THREAD

**Issue by plasticmacaroni** [ebiten/ebiten.org#54]
_https://ebiten.org/documents/1.12.html_

Regarding the page above, I understand that rotation can affect the borders between tiles when using SubImage(). However, I am importing PNGs directly to use in tiling, with no spaces around each tile's pixels on each PNG.

Before updating to 1.12, the tiles are flush against one another (I have a simple function set that places them adjacently). After updating, the tiles in my scene appear to have small gaps, making the (black) background visible between them. 

I can continue to debug what's going on here, but believe that the back-end updates to 1.12 before they're sent to the GPU are causing this behavior change. 

This problem may well be PEBKAC, and I could be misunderstanding some element of vector math etc. However, to reproduce this, all I have to do is change the import from 1.11.x to 1.12.x.

If there is any advice/a particular place for me to look in order to update my code and therefore be able to update the version number, I'd love to hear any and all advice! Thank you very much :)

**Comment by hajimehoshi** [comment]
(I'll transfer this issue to hajimehosh/ebiten later)

Sorry but I'm not sure what was the problem. You used your own texture atlas without gaps, and after updating to Ebiten 1.12, you saw some unexpected pixels?
