### ISSUE TITLE
auto focus on wasm Ebiten game?

### ISSUE THREAD

**Issue by jsantore** [ebiten/ebiten.org#59]
https://ebiten.org/documents/webassembly.html

Having followed the steps in the page above to embed my ebiten game into a web page with wasm, I find that the games does not have focus until clicked on. This behavior occurs on both firefox and chromium. Perhaps you could add another step in the directions to make game the focus upon load?

**Comment by hajimehoshi** [comment]
Hm, this sounds like a web programming that might not be related to Ebiten. I'm not sure. Let me think.

Thank you for the suggestion!

**Comment by hajimehoshi** [comment]
By default, the game should run even when the game is unfocused (as of v2). Have you tried v2?

**Comment by jsantore** [comment]
The game runs automatically, it just doesn't take keyboard input without gaining focus via the mouse. I'm sure it is a web programming issue, I was just wonder if the tutorial which mentions how to embed the game in a web page via webassemby might also mention how to automatically give it focus. I'll try a few things.

thanks

**Comment by hajimehoshi** [comment]
Ah yes, the first inputting is a general web programming issue, and I'm sure this is not an Ebiten issue. The first focused element should be determined by the browser or the web author, and personally I don't think this is a good behavior to focus an iframe automatically just after loading a page.
