### ISSUE TITLE
Provided WASM JS 

### ISSUE THREAD

**Issue by goshlanguage** [ebiten/ebiten.org#67]
https://ebiten.org/documents/webassembly.html

Firstly, thanks for this project, it's been really fun to work with. 

I was following the steps outlined in the documentation above, when I encountered a JS error stemming from the `fetch()` request in the provided javascript. 

```js
main.html:13 Fetch API cannot load file:///Users/ryan/go/src/github.com/goshlanguage/bento/assets/web/bento.wasm. URL scheme "file" is not supported.

(anonymous) @ main.html:13
main.html:13         Uncaught (in promise) TypeError: Failed to fetch
    at main.html:13:34
```

I believe this is due to Chrome itself, and it's CORS policy. Perhaps a note in the documents to detail this would potentially prevent others time triaging the matter if they run into it as well?
 
 I think this was what was intended by the snippet:
 
 > You might need a local HTTP server

**Comment by hajimehoshi** [comment]
Yeah, file:// URL might not work well in this case, and that's what I intended. Have you tried `wasmserve` https://github.com/hajimehoshi/wasmserve?

**Comment by goshlanguage** [comment]
I have, another great project. 

In this instance I believe your other documentation on leveraging `embed` was what I ended up with. My target is Github pages so I'm not sure that I could leverage `wasmserve`.
