### ISSUE TITLE
Self-host fonts

### ISSUE THREAD

**Issue by tslocum** [ebiten/ebiten.org#68]
Serving these assets via Google results in all visitors who wish to see ebiten.org as it was intended being tracked.  Users may block these assets from being served (due to privacy concerns), but this will result in a degraded viewing experience, as browsers must then fall back to a font that is installed on the user's system.

> ... Users of Google Web Fonts are bound by [Google's generic API terms of service](https://developers.google.com/terms/), which includes this clause:
>
>    By using our APIs, you agree that Google can use submitted information in accordance with our privacy policies, such as http://www.google.com/privacypolicy.html.
>
> Google's [privacy policy](http://www.google.com/policies/privacy/#infocollect) allows it to collect a large amount of data about users of its services, both to improve the service and to support it commercially. This includes log data (e.g. browser version) and location data (the IP address of your site's visitors). Sites that use Google Web Fonts are feeding data back to Google. ...

From https://webmasters.stackexchange.com/questions/60464/are-there-privacy-considerations-in-using-google-web-fonts

**Comment by hajimehoshi** [comment]
Hi,

Even if Google font (Roboto) is not available, the site doesn't degrade its view so much. Or, have you found critical differences?

I don't have a strong opinion on self-hosting so far.

**Comment by tslocum** [comment]
That is true.  Users' privacy being violated and the lack of consent to being tracked for commercial purposes, in exchange for hosting a font remotely, is my main concern.

**Comment by hajimehoshi** [comment]
Does this mean we should not use Google font for any websites?

**Comment by hajimehoshi** [comment]
Continued to https://github.com/ebitengine/ebitengine.org/issues/2
