### ISSUE TITLE
Grammar error on Install.html

### ISSUE THREAD

**Issue by jlafleur93** [ebiten/ebiten.org#70]
https://ebiten.org/documents/install.html
![Ebiten](https://user-images.githubusercontent.com/50718377/168129814-e4a5ddbe-aa07-4697-9496-81e722e4dd72.PNG)
Hi, very cool work. 

This is a small issue, and was wondering if the following would be a good replacement for the lines in the image included.
```
If you see this window with a rotating Gophers image, congratulations!

You have sucessfully installed Ebiten!
```

**Comment by hajimehoshi** [comment]
Fixed
